### ISSUE TITLE
varid

### ISSUE THREAD

**Issue by visr** [Alexander-Barth/NetCDF3#1]
Do you think it'd make sense to make the varid 1-based, such that it can always be used directly as an index? Right now there many `index = varid + 1` lines out there.

**Comment by Alexander-Barth** [comment]
Indeed. With a zero-based `varid`, the testing with libnetcdf is a bit simpler as the NetCDF3 function use the same arguments than the corresponding function in libnetcdf (except for ncid).
But I am considering to wrap the id in a parametric julia struct (including also the type and the dimensional) so that `nc_get_var(ncid,varid)` becomes type-stable.
